#:schema node_modules/wrangler/config-schema.json
name = "github-sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "08cec91d7dc840ba874ca0835c3bfe06" }
]

[assets]
directory = "./public"
